### PR TITLE
Feature/add backend

### PR DESCRIPTION
**Pull request by Jdellis818**

### CODE REVIEW

**Review by charkour — CHANGES_REQUESTED** [review]
Looks good so far. Thanks for translating it to TS! I have a couple quick comments to make this better. 
Console logs are good for debugging, but I think it would be better to send some sort of 400 if there is an error it the queries. Also, instead of adding ESLint disable comments, it's good to either update the ESLint config or try to resolve them in the files. If a rule is too strict, we can change it. 
I added a pre-commit hook as well to auto-format, lmk if it gives you any issues.

**Comment by charkour** [comment]
There was one importing ESLint error I couldn't resolve, could use some more time to fiddle with it.

**Comment by Jdellis818** [comment]
I just fixed some of the eslint issues and added some very basic error handling

**Review by charkour — APPROVED** [review]
The error handling looks nice. We can make it more robust later. The postinstall command also looks like it will be helpful. Thanks for the changes.

**Pull request merged**
