### PR TITLE
add gh action to run tests

### PR DESCRIPTION
**Pull request by charkour**
This is my first time writing GH actions, but it is supposed to install the packages and test the apps on each PR.

### CODE REVIEW

**Comment by charkour** [comment]
hmm this is taking a long time

**Comment by Jdellis818** [comment]
```
 FAIL  src/components/reusables/__tests__/StyledText-test.jsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\Admin\Documents\KnightHaven\super-turtle-tracker\client-super-turtle-tracker\src\components\reusables\__tests__\StyledText-test.jsx:1
    import * as React from "react";
           ^

    SyntaxError: Unexpected token *

      at Runtime._execModule (node_modules/jest/node_modules/jest-runtime/build/index.js:1179:56)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.067 s
Ran all test suites.

Watch Usage
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
```
This is the log I get when running `npm test`. It waits at the end for a response from the user

**Comment by charkour** [comment]
Ah okay, I'll fix that. Thanks

**Review by Jdellis818 — APPROVED** [review]
LGTM

**Pull request merged**
